"""add price_bars and stock_status tables

Revision ID: 0d812a03dccc
Revises: 1d543cda5a15
Create Date: 2026-07-28 22:08:43.273464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d812a03dccc'
down_revision: Union[str, Sequence[str], None] = '1d543cda5a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'timestamp', name='uix_symbol_interval_timestamp')
    )
    op.create_index(op.f('ix_price_bars_interval'), 'price_bars', ['interval'], unique=False)
    op.create_index(op.f('ix_price_bars_symbol'), 'price_bars', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_bars_timestamp'), 'price_bars', ['timestamp'], unique=False)
    op.create_table('stock_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_bar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_bar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('total_bars', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_status_interval'), 'stock_status', ['interval'], unique=False)
    op.create_index(op.f('ix_stock_status_symbol'), 'stock_status', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_status_symbol'), table_name='stock_status')
    op.drop_index(op.f('ix_stock_status_interval'), table_name='stock_status')
    op.drop_table('stock_status')
    op.drop_index(op.f('ix_price_bars_timestamp'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_symbol'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_interval'), table_name='price_bars')
    op.drop_table('price_bars')
    # ### end Alembic commands ###
