"""create backtests stocks user_strategies tables

Revision ID: 1d543cda5a15
Revises: 
Create Date: 2026-07-28 21:50:49.088393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1d543cda5a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capital_per_trade', sa.Float(), nullable=False),
    sa.Column('segment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy_ids', sa.JSON(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('params_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_created_at'), 'backtests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtests_params_hash'), 'backtests', ['params_hash'], unique=False)
    op.create_index(op.f('ix_backtests_public_id'), 'backtests', ['public_id'], unique=True)
    op.create_index(op.f('ix_backtests_symbol'), 'backtests', ['symbol'], unique=False)
    try:
        op.drop_index(op.f('ix_backtestrun_symbol'), table_name='backtestrun')
    except Exception:
        pass
    try:
        op.drop_table('backtestrun')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtestrun',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('start', sa.VARCHAR(), nullable=False),
    sa.Column('end', sa.VARCHAR(), nullable=False),
    sa.Column('interval', sa.VARCHAR(), nullable=False),
    sa.Column('capital_per_trade', sa.FLOAT(), nullable=False),
    sa.Column('segment', sa.VARCHAR(), nullable=False),
    sa.Column('strategy_ids', sqlite.JSON(), nullable=True),
    sa.Column('result_json', sqlite.JSON(), nullable=True),
    sa.Column('pdf_path', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtestrun_symbol'), 'backtestrun', ['symbol'], unique=False)
    op.drop_index(op.f('ix_backtests_symbol'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_public_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_params_hash'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_created_at'), table_name='backtests')
    op.drop_table('backtests')
    # ### end Alembic commands ###
